### ISSUE TITLE
Encrypt and decrypt large files

### ISSUE THREAD

**Issue by riccardoratta** [firstfloorsoftware/flutter_sodium#11]
With Flutter is possible to read and write files through streams, this is very good if you have to do operations on large files because it's not necessary to store the entire file on the memory (also very limited on mobile devices).

It's possible with this library, even in theory,  to decrypt and encrypt files with stream?

**Comment by kozw** [comment]
Certainly possible. This plugin doesn't support crypto_secretstream_xchacha20poly1305 yet, but should.
