### ISSUE TITLE
Use Dart VM FFI

### ISSUE THREAD

**Issue by kozw** [firstfloorsoftware/flutter_sodium#12]
The [Flutter 2019 roadmap](https://github.com/flutter/flutter/wiki/Roadmap) lists better support for C/C++ libraries from Flutter, including direct calls to C/C++ from Dart. This is of major importance for flutter_sodium. The current implementation uses platform channels with Java and Swift interop. 

Not only is the runtime performance sub-optimal, there's a lot of code to write and maintain. Not to mention the fact that the Android version is still lacking in features compared to iOS due to a dependency on incomplete 3rd party libraries (#7)

As soon as native C interop is available, flutter_sodium should take advantage of it. You can track the [Dart issue](https://github.com/dart-lang/sdk/issues/34452) and read more in the [FFI vision document](https://gist.github.com/mraleph/2582b57737711da40262fad71215d62e). Looks like an initial version is planned somewhere in Q1 2019.

**Comment by filleduchaos** [comment]
Hello @kozw - is there any work being done on this now that `dart:ffi` is in preview? I see there's an `ffi` branch, but it hasn't been touched in 6 months. I'm open to contributing if you're short on time/resources :)

**Comment by kozw** [comment]
Not at the moment no, indeed due to limited time and resources. I'm not sure the current ffi branch even compiles with the latest preview bits. Feel free to start creating pull requests.

**Comment by cbenhagen** [comment]
@kozw Maybe you could team up with Marvin Hannot? (https://gitlab.com/MagicGuitar/dart-sodium)

**Comment by MarvinHannott** [comment]
As far as I know, the FII doesn't work (yet) with AOT compilation. And calls aren't asynchronous like calls to Flutter's `MethodChannel`. But if you think my work is of any help, please feel free to use it.

**Comment by cbenhagen** [comment]
FFI does now work with AOT. See https://github.com/dart-lang/sdk/issues/35765 and https://github.com/dart-lang/sdk/issues/37295.

**Comment by canewsin** [comment]
@cbenhagen is there any documentation on usage ?

**Comment by kozw** [comment]
Porting flutter_sodium to FFI has recently been started. Track its progress in #35. Closing this issue
