### ISSUE TITLE
Build warning on android

### ISSUE THREAD

**Issue by dbenninger** [firstfloorsoftware/flutter_sodium#2]
flutter_sodium works fine, thanks for the great work. I do get a deprecation warning when building on Android though:

Configuration 'compile' in project ':flutter_sodium' is deprecated. Use 'implementation' instead.

Versions:
flutter_sodium: "^0.0.4"
Gradle 4.8
Flutter 0.5.1

**Comment by kozw** [comment]
Valid point, will be looked at.
