### ISSUE TITLE
KeyDerivation.deriveFromKey hard-coded context

### ISSUE THREAD

**Issue by lukasgit** [firstfloorsoftware/flutter_sodium#25]
Hi @kozw I'm curious if there is or was a reason why KeyDerivation.deriveFromKey(masterKey, subKeyId, subKeyLength) implicitly differs from Sodium.cryptoKdfDeriveFromKey(subKeyLength, subKeyId, context, masterKey) ?

This plugin currently ignores user-defined context by using hard-coded String context = '00000000'

Also, for consistency, why not follow the same input structure as Sodium.cryptoKdfDeriveFromKey(subKeyLength, subKeyId, context, masterKey) ?

https://github.com/firstfloorsoftware/flutter_sodium/blob/master/lib/src/key_derivation.dart

**Comment by kozw** [comment]
Sodium.cryptoKdfDeriveFromKey is the low-level API that provides a 1:1 mapping to libsodium functions.

KeyDerivation is part of the high-level, opinionated API, providing a more dart-like experience. This should explain the difference in input structure.
The context parameter value '00000000' is just a default, you can simply provide your own value (which must be 8 chars long). I'm assuming only a single context is used in an app, this is possibly an incorrect assumption. Yes, it is opinionated, and yes can easily provide your own value.

Does that make sense?

**Comment by lukasgit** [comment]
Yes, makes sense. Thank you for clarifying, thank you for providing the low-level Sodium API, and most of all thank you for this Flutter package!
