### ISSUE TITLE
cryptoBoxSeal not returning anything.

### ISSUE THREAD

**Issue by pneves001** [firstfloorsoftware/flutter_sodium#3]
This is a bit of a strange issue.  I'm not getting an error, or any kind of response from the function what so ever. It just does nothing.  The following code is what I'm using to call the function. The execution just stops when the function is called although my flutter app continues to operate. 

   var encoder = new JsonEncoder();

    var jsonencoded = encoder.convert(data);

    var jsonBeforeSeal = utf8.encode(jsonencoded);
    
            print("Data before seal.");
            print(jsonBeforeSeal);

            print("Public Key");
            print(_publicKey);

            Uint8List response = await Sodium.cryptoBoxSeal(jsonBeforeSeal, utf8.encode(_publicKey));

The public key is returned from my server in hex format and worked in my ionic version of my app.

**Comment by kozw** [comment]
Interesting, Android or iOS, or both?

**Comment by pneves001** [comment]
I haven't tried ios. So right now android. But I will let you know about IOS.

**Comment by pneves001** [comment]
I can confirm I get the exact same result in both. Although to get the IOS version to compile I had to add the following line to the podfile:

use_frameworks!

I'm using a newer version of swift 3.2 so when I put the following line in it didn't compile:
config.build_settings['SWIFT_VERSION'] = '3.2'

But the behavior is the same in both IOS and Android at this time.

**Comment by pneves001** [comment]
I have been looking into this issue a bit because it's a bit of a show stopper for me.  I really need to get this package working. More specifically when comparing this package with the cordova-plugin-minisodium package for cordova. The two packages are similar. The cordova plugin has both the libsodium-jni project and the libsodium project as dependencies. this project appears to just have the libsodium-jni project and omits the libsodium project. Does this not need both to work? I think flutter_sodium is missing a dependency judging from what I can see here.

**Comment by kozw** [comment]
I'm not sure the libsodium dependency is required for Android. For iOS the binary is included. I'm running both Android and iOS, and both work fine.

Are you running in an emulator or an actual device? Have you tried running the example app that is included in GitHub?

**Comment by kozw** [comment]
Looking at your code snippet: you're doing an utf8.encode on a string in hex-format. You probably do want to do hex.decode (instead of utf8.encode). Also, make sure you pubkey consists of 32 bytes.

**Comment by pneves001** [comment]
Thank you.  I will try this. I am currently running it on an actual device with the latest version of Android.

**Comment by pneves001** [comment]
Thank you this worked. I have it working now.
