### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by Rakshak1344** [firstfloorsoftware/flutter_sodium#36]
```
$ flutter test
00:11 +1 -1: Unlock FundRaiser Identity [E]                                                                                         
  MissingPluginException(No implementation found for method crypto_sign_seed_keypair on channel flutter_sodium)
  package:flutter/src/services/platform_channel.dart 154:7  MethodChannel._invokeMethod
  
00:12 +1 -1: Some tests failed.     
```
I have no Issues implementing the package, But when I test it. I get this issue.

**Comment by kozw** [comment]
The flutter_sodium test cases do not exist due to the nature of platform channels, this will change with the ffi implementation.

**Comment by Rakshak1344** [comment]
Will I be able to test my function? If so how to do it with ffi implementation?

**Comment by kozw** [comment]
Yes, you should be able to implement your own tests with flutter_sodium in the ffi scenario. The test runs in the scope of your host os (mac, win, linux), so you need to have libsodium installed on your os. See also the libsodium installation instructions at https://doc.libsodium.org/

**Comment by qdm12** [comment]
Hello, thanks for the great library 👍 I have a question related to this issue regarding support for desktop platforms using [go-flutter](https://github.com/go-flutter-desktop/go-flutter).

As libsodium doesn't come on desktop OSes, I guess I would encounter the problem as well (as it does on unit tests). Is there any plan on implementing some cryptographic functions in dart without ffi, at least as a backup in the case when the native ffi doesn't exist?

Thanks!!
