### ISSUE TITLE
XChaCha20-Poly1305-IETF Usage

### ISSUE THREAD

**Issue by jeprojects** [firstfloorsoftware/flutter_sodium#4]
Thanks for putting together this package.

Is there anyway to get access to libsodiums XChaCha20-Poly1305-IETF?

**Comment by kozw** [comment]
It should be no problem to add chacha20poly1305. However since xchacha20poly1305 is the preferred AEAD construction, this needs to be fixed. Look like I need to dive into libsodium-jni.

**Comment by jeprojects** [comment]
Awesome work. Thanks!

**Comment by jeprojects** [comment]
I just noticed that libsodium jni also has secret stream high-level api available which uses xchacha20poly1305.

https://github.com/joshjdevl/libsodium-jni/blob/master/src/test/java/org/libsodium/jni/crypto/SecretStreamTest.java

https://download.libsodium.org/doc/secret-key_cryptography/secretstream.html

**Comment by jeprojects** [comment]
https://github.com/joshjdevl/libsodium-jni/issues/116
