### ISSUE TITLE
Invalid plugin specification flutter_sodium.

### ISSUE THREAD

**Issue by sh3rlock97** [firstfloorsoftware/flutter_sodium#42]
Since the newest update, I get an error when running my project:

```
Invalid plugin specification flutter_sodium.
Cannot find the `flutter.plugin.platforms` key in the `pubspec.yaml` file. An instruction to format the `pubspec.yaml` can be found here: https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms
```

Has someone found a bugfix for that?

I found a similar error in another package (https://github.com/simolus3/moor/issues/727#issuecomment-662935493) but I can't adapt the changes to this project.

**Comment by kozw** [comment]
What version of flutter are your using? And is this happening in the emulator or an actual device?
