### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by kozw** [firstfloorsoftware/flutter_sodium#53]
See title

**Comment by kozw** [comment]
Migration is complete, publishing to pub.dev is blocked because of following warning:

```
package:sky_engine/js/js_dart2js.dart is opting out of null safety
```

See also https://github.com/dart-lang/sdk/issues/44567

**Comment by ccadieux** [comment]
@kozw Great work. Thank you for your commitment to this project.

**Comment by kozw** [comment]
A prerelease version of flutter_sodium with null safety built-in is now available on pub.dev. Closing this issue now.
