### ISSUE TITLE
Cannot use libsodium

### ISSUE THREAD

**Issue by maerlynflagg** [firstfloorsoftware/flutter_sodium#54]
i import the package and i do before any encryption call  i do 

`Sodium.init();`

but on some devices there came a exception:

`dlopen failed: library "libsodium.so" not found`

Screen of user:

<details>

![Screenshot_20210106-112014](https://user-images.githubusercontent.com/13437496/103878692-0fe83900-50d7-11eb-9a11-c17c521c636f.png)

</details>

is it a bug? 
or did i miss something?

do you have any idea, what the problem is?

**Comment by kozw** [comment]
Doesnt look good, couple of questions:

- what version of flutter and flutter_sodium are you using?
- can you be more specific on the devices where flutter_sodium fails?

This is not necessarily related to specific devices, but could also be related to culture/language settings. If you can share as much info as possible, that would be great.

Thanks.

**Comment by maerlynflagg** [comment]
this issue hasn't every user.  so i thought it's device specific. 
but currently i haven't details from the users device.

flutter_sodium version:

`flutter_sodium: ^0.1.10`

flutter doctor -v:

<details>

Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

Lernen Sie das neue plattformübergreifende PowerShell kennen – https://aka.ms/pscore6

PS C:\tfs\VisitCube-Lite> flutter doctor -v
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.685], locale de-DE)
    • Flutter version 1.22.5 at C:\Users\...\flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3) 
    • Android SDK at C:\Users\...\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\...\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\...\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.    
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.52.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
PS C:\tfs\VisitCube-Lite> 

</details>

**Comment by maerlynflagg** [comment]
I got some device infos:

- HTC device
- language setting is german like a lot of our users
- Android 6 is the current OS

**Comment by kozw** [comment]
There might be an issue with Android 6 and older versions, as described in https://github.com/flutter/flutter/issues/73318.

Looks like there is a possible workaround, that you'll need to apply in your Android's App java code. See https://github.com/flutter/flutter/issues/73318#issuecomment-754598119

**Comment by maerlynflagg** [comment]
okay, thanks. workaround looks simple.

**Comment by vishnukvmd** [comment]
@kozw I'm running into the same issue on a few devices that I unfortunately do not have access to.

https://github.com/flutter/flutter/issues/73318#issuecomment-754598119 suggests two work-arounds.

My [settings.gradle](https://github.com/ente-io/frame/blob/master/android/settings.gradle) already resembles the first work-around, so there's nothing to change there.

As for the second, it looks to me like it's supposed to be part of the plugin's Java code? https://github.com/firstfloorsoftware/flutter_sodium/pull/63 perhaps?

**Comment by vishnukvmd** [comment]
#63 triggers https://github.com/flutter/flutter/issues/83613, so closing that.

@kozw @maerlynflagg Could you please tell me to where I'm supposed to add this workaround? Is there sample code I can draw inspiration from? Thank you!
