### ISSUE TITLE
Support for FFI 1.0

### ISSUE THREAD

**Issue by pheki** [firstfloorsoftware/flutter_sodium#59]
[Dart 2.12](https://medium.com/dartlang/announcing-dart-2-12-499a6e689c87) has been released, and with it, both null safety and [FFI](https://dart.dev/guides/libraries/c-interop) are now stable.

I see that you have null-safety already in a pre-release, but can FFI be migrated as well? I can't update some of my dependencies (namely `shared_preferences`) as it depends on ffi 1.0

Thanks a lot :)

**Comment by maerlynflagg** [comment]
yes, it would be very nice, if you can update to FFI 1.0.

path_provider is in conflict to:

```
Because path_provider >=2.0.0 depends on path_provider_windows ^2.0.0 which depends on ffi ^1.0.0, path_provider >=2.0.0 requires ffi ^1.0.0.

And because flutter_sodium 0.1.11 depends on ffi ^0.1.3 and no versions of flutter_sodium match >0.1.11 <0.2.0, path_provider >=2.0.0 is incompatible with flutter_sodium ^0.1.11.
```

**Comment by kozw** [comment]
Working on it

**Comment by kozw** [comment]
And done, flutter_sodium 0.2.0 available in pub.dev

**Comment by maerlynflagg** [comment]
Nice, before i gave you a pull request today  to support you. thanks :)

**Comment by gargakshit** [comment]
Also why not remove the [Known Issues](https://github.com/firstfloorsoftware/flutter_sodium#known-issues) part now as FFI is stable now
