### ISSUE TITLE
Add a xchacha version of crypto_box_seal

### ISSUE THREAD

**Issue by jeprojects** [firstfloorsoftware/flutter_sodium#6]
Is it possible to add a version of Sodium.cryptoBox* to use XChaCha20 instead of XSalsa20?

libsodium already support this although undocumented:
https://github.com/jedisct1/libsodium/commit/ccb842f4884aa8917dcbba79509a349f8c475b3c

**Comment by jeprojects** [comment]
I have added the necessary code to libsodium-jni in a pull request (if it gets approved).

https://github.com/joshjdevl/libsodium-jni/pull/115

**Comment by kozw** [comment]
That should not be a problem

**Comment by jeprojects** [comment]
Any chance you could get this one added soon?

**Comment by kozw** [comment]
Didn't notice it was already merged in libsodium-jni. I have a working Android version, iOS doesn't work yet. Hoping to have a new version soon.

**Comment by kozw** [comment]
Available in v0.0.8
