### ISSUE TITLE
Missing libsodiumjni APIs (Android)

### ISSUE THREAD

**Issue by kozw** [firstfloorsoftware/flutter_sodium#7]
**IMPORTANT NOTE**
I'm currently porting flutter_sodium to FFI. The goal is to achieve 100% API coverage with FFI. The platform channel implementation is still maintained, but there are no plans to fix the missing APIs.

Several APIs are not available on Android. This is the complete list of libsodiumjni APIs that are missing or malfunctioning:
- [x] ~~crypto_aead_chacha20poly1305_encrypt_detached~~
- [x] ~~crypto_aead_chacha20poly1305_decrypt_detached~~
- [x] ~~crypto_aead_chacha20poly1305_keygen~~
- [x] ~~crypto_aead_chacha20poly1305_ietf_encrypt_detached~~
- [x] ~~crypto_aead_chacha20poly1305_ietf_decrypt_detached~~
- [x] ~~crypto_aead_chacha20poly1305_ietf_keygen~~
- [x] ~~crypto_aead_xchacha20poly1305_ietf_encrypt~~
- [x] ~~crypto_aead_xchacha20poly1305_ietf_decrypt~~
- [x] ~~crypto_aead_xchacha20poly1305_ietf_encrypt_detached~~
- [x] ~~crypto_aead_xchacha20poly1305_ietf_decrypt_detached~~
- [x] ~~crypto_aead_xchacha20poly1305_ietf_keygen~~
- [ ] crypto_auth_keygen (randombytes_buf fallback)
- [ ] crypto_generichash_keygen (randombytes_buf fallback)
- [x] crypto_kdf_keygen
- [x] crypto_kdf_derive_from_key
- [ ] crypto_onetimeauth_keygen (randombytes_buf fallback)
- [ ] crypto_pwhash_str_needs_rehash
- [ ] crypto_secretbox_keygen (randombytes_buf fallback)
- [ ] crypto_shorthash_keygen (randombytes_buf fallback)
- [ ] crypto_sign_init
- [ ] crypto_sign_update
- [ ] crypto_sign_final_create
- [ ] crypto_sign_final_verify
- [ ] randombytes_buf_deterministic
- [ ] sodium_version_string (this one is available but throws)

**Comment by jeprojects** [comment]
I tested the sodium_version_string method, its returns a byte[] and not a string.

This worked for me:

```
    public void Version() {
        Sodium sodium= NaCl.sodium();

        byte[] version = Sodium.sodium_version_string();

        version.toString();

        System.out.print(version);
    }
```

**Comment by jeprojects** [comment]
Added to following methods in a pull request: https://github.com/joshjdevl/libsodium-jni/pull/115

```
crypto_aead_chacha20poly1305_encrypt_detached 
crypto_aead_chacha20poly1305_decrypt_detached
crypto_aead_chacha20poly1305_keygen
crypto_aead_chacha20poly1305_ietf_encrypt_detached
crypto_aead_chacha20poly1305_ietf_decrypt_detached
crypto_aead_chacha20poly1305_ietf_keygen
crypto_aead_xchacha20poly1305_ietf_encrypt
crypto_aead_xchacha20poly1305_ietf_decrypt
crypto_aead_xchacha20poly1305_ietf_encrypt_detached
crypto_aead_xchacha20poly1305_ietf_decrypt_detached
crypto_aead_xchacha20poly1305_ietf_keygen
```

`crypto_aead_chacha20poly1305_ietf_encrypt`  already exists

**Comment by jeprojects** [comment]
Looks like my pull request was approved: joshjdevl/libsodium-jni#115

Feel free to update your libsodium-jni version from their git master and add the missing crypto_aead* and crypto_box_curve25519xchacha20poly1305 :)

**Comment by kozw** [comment]
Very cool. Working on it

**Comment by kozw** [comment]
Full crypto_aead_* support is now available in flutter_sodium 0.0.7

**Comment by ralkan** [comment]
Looks very promising! When could we expect secretbox to be implemented?

**Comment by jeprojects** [comment]
@ralkan SecretBox has already been implemented. There is just the one method `crypto_secretbox_keygen` that is currently using the randombytes_buf fallback.

**Comment by ralkan** [comment]
@jeprojects Cool, this is great! Thanks.

**Comment by rashedmyt** [comment]
is the list up-to-date.. I was wondering if the `crypto_sign_*` methods are working as expected on both android and ios..

**Comment by kozw** [comment]
The list is up-to-date, `crypto_sign_*` only works on iOS. I'm looking into alternative Android bindings, in order to bring Android support in line with iOS

**Comment by rashedmyt** [comment]
@kozw did you have a look at Google's tink library.. they support android

**Comment by MathiasDeWeerdt** [comment]
crypto_sign_ed25519_sk_to_curve25519 seems to be implemented but crypto_sign_ed25519_pk_to_curve25519 is not?

**Comment by kozw** [comment]
This issue is now obsolete with the current FFI implementation.
