### ISSUE TITLE
After upgrade to Xcode 10, flutter build fails with "Multiple commands produce..." error

### ISSUE THREAD

**Issue by kozw** [firstfloorsoftware/flutter_sodium#9]
Xcode 10 includes a new build system that fails with the following error when building a flutter app with the flutter_sodium plugin:

```Multiple commands produce '/[app_folder]/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework':```

Apparently any flutter iOS app with a dependency on CocoaPods will fail with this error. A [workaround](https://github.com/flutter/flutter/issues/20685#issuecomment-421511890) is available, you either can choose to fall back to the legacy build system, or update the iOS build settings.

Until this is fixed in the flutter tooling, you'll need to apply above workaround for iOS when using flutter_sodium in your flutter app.

**Comment by ROTGP** [comment]
Just FYI - I'm not experiencing any issues whatsoever with XCode 10 and flutter_sodium. I created the flutter project with swift support (as below), and didn't touch the podfile (it automatically specifies 'use_frameworks'). It built for iOS fine, and works as expected. I'm on Flutter 1.0.0 • channel stable. Thanks for your great work.

`flutter create -i swift my_app_name`

**Comment by kozw** [comment]
You are correct, this particular error no longer seem to occur. However, when creating a Flutter using Obj-C (which is the default), the [following workaround](https://github.com/firstfloorsoftware/flutter_sodium/issues/1#issuecomment-462179337) is still required:
